import type { GapStock, NewsItem, BacktestResult, ChartData, GapData } from './types'

export const mockGapStocks: GapStock[] = [
  {
    symbol: 'NVDA',
    company: 'NVIDIA Corporation',
    gapPercent: 3.2,
    price: 482.50,
    volume: 42500000,
    volumeRatio: 2.4,
    sentiment: 0.78,
    sentimentLabel: 'Bullish',
    historicalFillRate: 73,
    conviction: 'high',
    preMarketHigh: 485.20,
    preMarketLow: 478.90,
    vwap: 481.75,
    sector: 'Technology',
    marketCap: '1.2T',
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: 'TSLA',
    company: 'Tesla Inc',
    gapPercent: -2.8,
    price: 238.45,
    volume: 98500000,
    volumeRatio: 3.1,
    sentiment: 0.45,
    sentimentLabel: 'Neutral',
    historicalFillRate: 68,
    conviction: 'medium',
    preMarketHigh: 245.60,
    preMarketLow: 237.20,
    vwap: 240.15,
    sector: 'Consumer Cyclical',
    marketCap: '756B',
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: 'AAPL',
    company: 'Apple Inc',
    gapPercent: 1.8,
    price: 178.92,
    volume: 52300000,
    volumeRatio: 1.9,
    sentiment: 0.62,
    sentimentLabel: 'Bullish',
    historicalFillRate: 81,
    conviction: 'high',
    preMarketHigh: 179.45,
    preMarketLow: 177.80,
    vwap: 178.60,
    sector: 'Technology',
    marketCap: '2.8T',
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: 'AMD',
    company: 'Advanced Micro Devices',
    gapPercent: 4.5,
    price: 142.30,
    volume: 68900000,
    volumeRatio: 2.7,
    sentiment: 0.71,
    sentimentLabel: 'Bullish',
    historicalFillRate: 65,
    conviction: 'high',
    preMarketHigh: 143.80,
    preMarketLow: 139.50,
    vwap: 141.90,
    sector: 'Technology',
    marketCap: '230B',
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: 'META',
    company: 'Meta Platforms Inc',
    gapPercent: -1.5,
    price: 512.75,
    volume: 12400000,
    volumeRatio: 1.2,
    sentiment: 0.38,
    sentimentLabel: 'Bearish',
    historicalFillRate: 54,
    conviction: 'low',
    preMarketHigh: 520.30,
    preMarketLow: 511.90,
    vwap: 515.20,
    sector: 'Communication Services',
    marketCap: '1.3T',
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: 'MSFT',
    company: 'Microsoft Corporation',
    gapPercent: 2.1,
    price: 412.60,
    volume: 23800000,
    volumeRatio: 1.8,
    sentiment: 0.68,
    sentimentLabel: 'Bullish',
    historicalFillRate: 76,
    conviction: 'high',
    preMarketHigh: 413.50,
    preMarketLow: 408.90,
    vwap: 411.85,
    sector: 'Technology',
    marketCap: '3.1T',
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: 'GOOGL',
    company: 'Alphabet Inc',
    gapPercent: 1.3,
    price: 168.45,
    volume: 18200000,
    volumeRatio: 1.4,
    sentiment: 0.55,
    sentimentLabel: 'Neutral',
    historicalFillRate: 62,
    conviction: 'medium',
    preMarketHigh: 169.10,
    preMarketLow: 167.20,
    vwap: 168.15,
    sector: 'Communication Services',
    marketCap: '2.1T',
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: 'AMZN',
    company: 'Amazon.com Inc',
    gapPercent: -0.8,
    price: 195.30,
    volume: 34500000,
    volumeRatio: 1.1,
    sentiment: 0.42,
    sentimentLabel: 'Neutral',
    historicalFillRate: 58,
    conviction: 'low',
    preMarketHigh: 196.80,
    preMarketLow: 194.90,
    vwap: 195.75,
    sector: 'Consumer Cyclical',
    marketCap: '2.0T',
    lastUpdated: new Date().toISOString(),
  },
]

export const mockNews: NewsItem[] = [
  {
    title: 'NVIDIA Announces New AI Chip Architecture, Beating Analyst Expectations',
    source: 'Bloomberg',
    timestamp: '2 hours ago',
    sentiment: 0.85,
    url: '#',
  },
  {
    title: 'Tesla Q4 Deliveries Miss Estimates, Stock Opens Lower',
    source: 'Reuters',
    timestamp: '3 hours ago',
    sentiment: 0.32,
    url: '#',
  },
  {
    title: 'Apple Expands Manufacturing in India, Reduces China Dependence',
    source: 'CNBC',
    timestamp: '5 hours ago',
    sentiment: 0.68,
    url: '#',
  },
  {
    title: 'AMD Wins Major Server Contract with Tech Giant',
    source: 'WSJ',
    timestamp: '1 hour ago',
    sentiment: 0.78,
    url: '#',
  },
]

export const mockBacktestResult: BacktestResult = {
  strategy: 'Gap > 2% + Volume > 2x + Bullish Sentiment',
  totalTrades: 287,
  winRate: 78.4,
  profitFactor: 2.34,
  totalReturn: 42.7,
  maxDrawdown: -8.3,
  sharpeRatio: 1.89,
  avgWin: 2.8,
  avgLoss: -1.6,
  equityCurve: Array.from({ length: 90 }, (_, i) => ({
    date: new Date(Date.now() - (89 - i) * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    value: 10000 * (1 + ((i * 0.42) / 90) + (Math.random() - 0.5) * 0.05),
  })),
}

export const mockChartData: ChartData[] = [
  { time: '2026-01-13', open: 470.00, high: 475.20, low: 468.50, close: 474.80, volume: 38500000 },
  { time: '2026-01-14', open: 474.80, high: 478.90, low: 472.30, close: 476.20, volume: 42100000 },
  { time: '2026-01-15', open: 476.20, high: 481.50, low: 475.10, close: 479.60, volume: 39800000 },
  { time: '2026-01-16', open: 479.60, high: 482.30, low: 477.90, close: 478.40, volume: 35600000 },
  { time: '2026-01-17', open: 478.40, high: 483.60, low: 476.50, close: 482.50, volume: 42500000 },
]

// Convert GapStock format to GapData format for new API hooks
export const mockGaps: GapData[] = mockGapStocks.map((stock) => ({
  symbol: stock.symbol,
  name: stock.company,
  gapPercent: stock.gapPercent,
  currentPrice: stock.price,
  previousClose: stock.price / (1 + stock.gapPercent / 100),
  volume: stock.volume,
  avgVolume: stock.volume / stock.volumeRatio,
  volumeRatio: stock.volumeRatio,
  sentimentScore: stock.sentiment,
  historicalFillRate: stock.historicalFillRate,
  conviction: stock.conviction,
  sector: stock.sector,
  marketCap: stock.marketCap,
  preMarketHigh: stock.preMarketHigh,
  preMarketLow: stock.preMarketLow,
  vwap: stock.vwap,
}))
